title: Soumyajoy Kundu
description: Research interests in statistical machine learning, computer vision, and multimodal AI with an emerging interest in neuroAI domain.
markdown: kramdown

plugins:
  - jekyll-feed

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
